CREATE DATABASE SIGUE_CET;
USE SIGUE_CET;

#TABLAS

CREATE TABLE `PERFIL`(
`ID_PERFIL` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`NOMBRE_PERFIL` VARCHAR(50)
);
DESCRIBE PERFIL;
INSERT INTO PERFIL VALUES (1,"Administrador");
INSERT INTO PERFIL VALUES (2,"Controlador de notificaciones");
INSERT INTO PERFIL VALUES (3,"Controlador de atención a dudas");
INSERT INTO PERFIL VALUES (4,"Controlador de registro de asistencia");
SELECT * FROM PERFIL;	

CREATE TABLE `PROG_ACAD` (
`ID_PROG_ACAD` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`NOMBRE_PROG_ACAD` VARCHAR(50) NOT NULL,
`CLAVE_PROG_ACAD` VARCHAR(10) NOT NULL
);
DESCRIBE PROG_ACAD;
INSERT INTO PROG_ACAD VALUES (1,"Tronco Común","TC");
INSERT INTO PROG_ACAD VALUES (2,"Redes de Cómputo","RC");
INSERT INTO PROG_ACAD VALUES (3,"Sistemas automotrices","SA");
SELECT * FROM PROG_ACAD;

CREATE TABLE `GRUPO` (
`ID_GRUPO` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`ID_PROG_ACAD` INT UNSIGNED NOT NULL,
`GRUPO` VARCHAR(10) NOT NULL,
FOREIGN KEY (ID_PROG_ACAD) REFERENCES PROG_ACAD(ID_PROG_ACAD) ON DELETE CASCADE ON UPDATE CASCADE
);
DESCRIBE GRUPO;
INSERT INTO GRUPO VALUES (1,1,"1MI1");
INSERT INTO GRUPO VALUES (2,2,"3IM2");
INSERT INTO GRUPO VALUES (3,3,"5IM3");
SELECT * FROM GRUPO;

CREATE TABLE `USUARIO`(
`ID_USUARIO` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`NOMBRE` VARCHAR(50) NOT NULL,
`APELLIDO_PAT` VARCHAR(30) NOT NULL,
`APELLIDO_MAT` VARCHAR(30) NOT NULL,
`CORREO_ELEC` VARCHAR(100),
`CONTRASENA` VARCHAR(100) NOT NULL,
`TELEFONO` VARCHAR(20),
`ID_PERFIL` INT UNSIGNED NOT NULL,
FOREIGN KEY (`ID_PERFIL`) REFERENCES PERFIL(`ID_PERFIL`) ON DELETE CASCADE ON UPDATE CASCADE
);
DESCRIBE USUARIO;
INSERT INTO USUARIO VALUES (1,"Dante","Olmedo","Campos","dolmedoc@ipn.mx","12345678","5523947211",1);
INSERT INTO USUARIO VALUES (2,"Jorge Luis","León","Acevedo","jleona@ipn.mx","12345678","5574239632",2);
INSERT INTO USUARIO VALUES (3,"David","Morales","Rico","dmoralesr@ipn.mx","12345678","5529618534",3);
INSERT INTO USUARIO VALUES (4,"Carolina","Sánchez","Macedo","csanchez@ipn.mx","12345678","5552187265",4);
SELECT * FROM USUARIO;
#DROP TABLE USUARIO;

CREATE TABLE `ALUMNO`(
`ID_ALUMNO` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`NOMBRE` VARCHAR(50) NOT NULL,
`APELLIDO_PAT` VARCHAR(30) NOT NULL,
`APELLIDO_MAT` VARCHAR(30) NOT NULL,
`CORREO_ELEC` VARCHAR(100),
`TELEFONO_TUTOR` VARCHAR(20),
`NUM_BOLETA` VARCHAR(15),
`CURP` VARCHAR(20),
`URL_FOTO` VARCHAR(300),
`ID_GRUPO` INT UNSIGNED NOT NULL,
#`ID_PROG_ACAD` INT UNSIGNED NOT NULL,
FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO) ON DELETE CASCADE ON UPDATE CASCADE
#FOREIGN KEY (ID_PROG_ACAD) REFERENCES PROG_ACAD(ID_PROG_ACAD) ON DELETE CASCADE ON UPDATE CASCADE
);
DESCRIBE ALUMNO;
#DROP TABLE ALUMNO;
INSERT INTO ALUMNO VALUES (1,"Edson Guadalupe","Mera","Orozco","emerao@ipn.mx","7721454667","2019350431","MEOE001211HHGRRDA1","https://cdn.smehost.net/sonymusiccommx-mxprod/wp-content/uploads/2020/12/Garrix.jpg",1);
INSERT INTO ALUMNO VALUES (2,"Luis Mario","Hernández","Rojas","lmhdezr@ipn.mx","5512745632","2019310367","LMHR120499HMGLEYI3","https://media.resources.festicket.com/www/artists/Hardwell_New.jpg",2);
SELECT * FROM ALUMNO;

CREATE TABLE `ASISTENCIA` (
`ID_ASISTENCIA` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`ID_ALUMNO` INT UNSIGNED NOT NULL,
`FECHA` DATE,
`HORA_ENTRADA` TIME,
`HORA_SALIDA` TIME,
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO) ON DELETE CASCADE ON UPDATE CASCADE
);
DESCRIBE ASISTENCIA;
INSERT INTO ASISTENCIA VALUES (1,1,'2022-01-01','07:00','13:00');
SELECT * FROM ASISTENCIA JOIN ALUMNO ON ASISTENCIA.ID_ALUMNO=ALUMNO.ID_ALUMNO;


#CONSULTAS NUEVAS
SELECT * FROM ALUMNO JOIN USUARIO ON ALUMNO.ID_USUARIO=USUARIO.ID_USUARIO;	#UNION DE TODOS LOS DATOS DE DOS TABLAS

SELECT ALUMNO.ID_ALUMNO, ALUMNO.ID_USUARIO, USUARIO.NOMBRE, USUARIO.APELLIDO_PAT, USUARIO.APELLIDO_MAT, 
USUARIO.USUARIO, USUARIO.PASSWORD, USUARIO.CORREO_ELEC, USUARIO.TELEFONO, PERFIL.NOMBRE_PERFIL, 
USUARIO.URL_FOTO FROM ALUMNO
JOIN USUARIO ON ALUMNO.ID_USUARIO=USUARIO.ID_USUARIO
JOIN PERFIL ON USUARIO.ID_PERFIL=PERFIL.ID_PERFIL;

SELECT USUARIO.NOMBRE, USUARIO.APELLIDO_PAT, USUARIO.APELLIDO_MAT, USUARIO.CORREO_ELEC, PERFIL.NOMBRE_PERFIL
FROM USUARIO
JOIN PERFIL ON USUARIO.ID_PERFIL=PERFIL.ID_PERFIL;